stream.rules = [
    {
        matches = [
            { application.name = "high-tide" }
        ]
        actions = {
            update-props = {
                target.object = "rodecaster_music"
            }
        }
    }
]
