XDG_CONFIG_HOME=${HOME}/.config
XDG_DATA_HOME=${HOME}/.local/share
XDG_STATE_HOME=${HOME}/.local/state
XDG_CACHE_HOME=${HOME}/.cache
XDG_BIN_HOME=${HOME}/.local/bin
XDG_DATA_DIRS=/usr/local/share:/usr/share
XDG_CONFIG_DIRS=/etc/xdg
BASH_ENV=${XDG_CONFIG_HOME}/bash/bashenv
LESSHISTFILE=${XDG_STATE_HOME}/less/history
CARGO_HOME=${XDG_DATA_HOME}/cargo
RUSTUP_HOME=${XDG_DATA_HOME}/rustup
GOBIN=${XDG_BIN_HOME}
GOCACHE=${XDG_CACHE_HOME}/go-build
GOMODCACHE=${XDG_CACHE_HOME}/go/mod
PYTHON_EGG_CACHE=${XDG_CACHE_HOME}/python-eggs
MYPY_CACHE_DIR=${XDG_CACHE_HOME}/mypy
RUFF_CACHE_DIR=${XDG_CACHE_HOME}/ruff
UV_CACHE_DIR=${XDG_CACHE_HOME}/uv
UV_PYTHON_CACHE_DIR=${XDG_CACHE_HOME}/uv/python
UV_PYTHON_INSTALL_DIR=${XDG_DATA_HOME}/uv/python
UV_TOOL_DIR=${XDG_DATA_HOME}/uv/tools
UV_TOOL_BIN_DIR=${XDG_BIN_HOME}
PIPX_HOME=${XDG_DATA_HOME}/pipx
PIPX_BIN_DIR=${XDG_BIN_HOME}
PYENV_ROOT=${XDG_DATA_HOME}/pyenv
POETRY_HOME=${XDG_DATA_HOME}/pypoetry
POETRY_CONFIG_DIR=${XDG_CONFIG_HOME}/pypoetry
POETRY_CACHE_DIR=${XDG_CACHE_HOME}/pypoetry
POETRY_DATA_DIR=${XDG_DATA_HOME}/pypoetry
BUN_INSTALL=${XDG_DATA_HOME}/bun
BUN_INSTALL_CACHE_DIR=${XDG_CACHE_HOME}/bun/install/cache
BUN_INSTALL_GLOBAL_DIR=${XDG_DATA_HOME}/bun/install/global
BUN_INSTALL_BIN=${XDG_BIN_HOME}
BUN_RUNTIME_TRANSPILER_CACHE_PATH=${XDG_CACHE_HOME}/bun/transpiler
COREPACK_HOME=${XDG_CACHE_HOME}/corepack
NODE_REPL_HISTORY=${XDG_STATE_HOME}/node/repl_history
GRADLE_USER_HOME=${XDG_DATA_HOME}/gradle
NPM_CONFIG_USERCONFIG=${XDG_CONFIG_HOME}/npm/npmrc
NPM_CONFIG_CACHE=${XDG_CACHE_HOME}/npm
NPM_CONFIG_PREFIX=${XDG_DATA_HOME}/npm
NPM_CONFIG_LOGS_DIR=${XDG_STATE_HOME}/npm/logs
PNPM_HOME=${XDG_DATA_HOME}/pnpm
NVM_DIR=${XDG_DATA_HOME}/nvm
NODENV_ROOT=${XDG_DATA_HOME}/nodenv
N_PREFIX=${XDG_DATA_HOME}/n
YARN_CACHE_FOLDER=${XDG_CACHE_HOME}/yarn
PUB_CACHE=${XDG_DATA_HOME}/pub-cache
DOCKER_CONFIG=${XDG_CONFIG_HOME}/docker
K9SCONFIG=${XDG_CONFIG_HOME}/k9s
HELM_CACHE_HOME=${XDG_CACHE_HOME}/helm
HELM_CONFIG_HOME=${XDG_CONFIG_HOME}/helm
HELM_DATA_HOME=${XDG_DATA_HOME}/helm
MISE_CONFIG_DIR=${XDG_CONFIG_HOME}/mise
MISE_DATA_DIR=${XDG_DATA_HOME}/mise
MISE_CACHE_DIR=${XDG_CACHE_HOME}/mise
MISE_STATE_DIR=${XDG_STATE_HOME}/mise
STARSHIP_CONFIG=${XDG_CONFIG_HOME}/starship.toml
STARSHIP_CACHE=${XDG_CACHE_HOME}/starship
FORGE_CONFIG=${XDG_CONFIG_HOME}/forge
EMACSDIR=${XDG_CONFIG_HOME}/emacs
DOOMDIR=${XDG_CONFIG_HOME}/doom
DOOMPROFILE=default
GTK_USE_PORTAL=1
PATH=${EMACSDIR}/bin:${XDG_BIN_HOME}:${CARGO_HOME}/bin:${BUN_INSTALL}/bin:${NPM_CONFIG_PREFIX}/bin${PATH:+:${PATH}}
