XDG_CONFIG_HOME=${HOME}/.config
XDG_DATA_HOME=${HOME}/.local/share
XDG_STATE_HOME=${HOME}/.local/state
XDG_CACHE_HOME=${HOME}/.cache
XDG_BIN_HOME=${HOME}/.local/bin
EMACSDIR=${XDG_CONFIG_HOME}/emacs
DOOMDIR=${XDG_CONFIG_HOME}/doom
DOOMPROFILE=default
PATH=${EMACSDIR}/bin:${XDG_BIN_HOME}${PATH:+:${PATH}}
